import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

const root = process.cwd();
const html = readFileSync(join(root, "src/renderer/selector/index.html"), "utf8");
const css = readFileSync(join(root, "src/renderer/selector/selector.css"), "utf8");
const script = readFileSync(join(root, "src/renderer/selector/selector.js"), "utf8");
const preload = readFileSync(join(root, "src/preload/selector-preload.cts"), "utf8");

describe("Desktop Selector UI", () => {
  it("提供工作区列表、Server 表单和明确删除确认", () => {
    expect(html).toContain("<title>选择工作区 - 叙界</title>");
    expect(html).toContain('aria-label="叙界工作区选择页"');
    expect(html).toContain("<small>桌面端</small>");
    expect(html).not.toContain("Scriverse Desktop");
    expect(html).toContain("选择工作区");
    expect(html).toContain("新增 Server");
    expect(html).toContain('id="local-ai-config-button"');
    expect(html).toContain('id="system-settings-button"');
    expect(html).toContain('id="local-server-port"');
    expect(html).toContain("本地服务首选端口");
    expect(html).toContain('min="10000" max="60000"');
    expect(html).toContain('id="log-storage-limit"');
    expect(html).toContain('id="open-log-directory"');
    for (const option of ["500 MB", "1 GB", "2 GB", "5 GB", "10 GB"]) expect(html).toContain(`>${option}</option>`);
    expect(html).toContain("app://desktop/local-ai/index.html");
    expect(html).toContain("id=\"profile-dialog\"");
    expect(html).toContain("id=\"local-setup-dialog\"");
    expect(html).toContain("id=\"local-login-dialog\"");
    expect(html).toContain("id=\"remote-login-dialog\"");
    expect(html).toContain("autocomplete=\"current-password\"");
    expect(html).not.toContain("Bearer");
    expect(html).not.toContain("浏览器 Cookie");
    expect(html).not.toContain("安全进程通道");
    expect(html).not.toContain("127.0.0.1");
    expect(html).not.toContain("最多 20 个端口");
    expect(script).not.toContain("独立浏览器分区");
    expect(script).not.toContain("Desktop 安全桥接");
    expect(html).toContain("autocomplete=\"new-password\"");
    expect(html).toContain("id=\"delete-dialog\"");
    expect(html).toContain("该 Server 的登录状态和本机副本将一并清除");
    expect(html).toContain("aria-live=\"polite\"");
    expect(script).toContain('error.code === "PROFILE_UNSYNCED_DATA"');
    expect(script).toContain("永久删除本机离线数据");
    expect(script).toContain("永久更换并删除本机副本");
    expect(script).toContain("bridge.profiles.status(profile.id)");
    expect(script).toContain('detail("Server 版本", profile.capabilities?.serverVersion ?? "未检测")');
    expect(script).toContain('window.addEventListener("focus", () => { void loadProfiles(); });');
    expect(script).toContain("localServerPort: Number(localServerPort.value)");
    expect(script).toContain("logStorageLimitMiB: Number(logStorageLimit.value)");
    expect(script).toContain("bridge.settings.openLogs()");
    expect(script).toContain('return { label: "本地", className: "idle" };');
    expect(css).toContain(".status-badge.idle {");
    expect(css).toContain(".dialog-fields input, .dialog-fields select {");
    expect(css).toContain("grid-template-columns: repeat(2, minmax(0, 1fr))");
    expect(css).toContain(".log-storage-setting-row .ghost-button { width: 100%; min-height: 45px;");
    expect(css).not.toContain(".status-badge.local {");
  });

  it("使用 DOM textContent 渲染 profile 并覆盖窄屏", () => {
    expect(script).toContain("node.textContent = text");
    expect(script).not.toContain("innerHTML");
    expect(css).toContain("@media (max-width: 430px)");
    expect(css).toContain(".app-header { align-items: stretch; flex-direction: column; }");
    expect(css).toContain(".brand strong, .brand small { white-space: nowrap; }");
    expect(css).toContain("overflow-wrap: anywhere");
    expect(css).toContain("width: min(184px, 100%); height: 60px");
    expect(css).not.toContain("width: min(260px, 100%)");
    expect(css).toContain("font-size: clamp(28px, 4vw, 38px)");
    expect(css).toContain("min-height: 38px; padding: 8px 14px; font-size: 11px");
  });

  it("preload 只暴露具名能力而不泄露通用 IPC", () => {
    expect(preload).toContain("contextBridge.exposeInMainWorld");
    expect(preload).toContain("selector:profiles:list");
    expect(preload).toContain("selector:profiles:status");
    expect(preload).toContain("selector:profiles:probe");
    expect(preload).toContain("selector:local:get-status");
    expect(preload).toContain("selector:local:setup");
    expect(preload).toContain("selector:local:login");
    expect(preload).toContain("selector:settings:get");
    expect(preload).toContain("selector:settings:update");
    expect(preload).toContain("selector:settings:open-logs");
    expect(preload).toContain("selector:remote:refresh-captcha");
    expect(preload).toContain("selector:remote:login");
    expect(preload).toContain("localAi: Object.freeze");
    expect(preload).toContain("selector:local-ai:configuration");
    expect(preload).toContain("selector:local-ai:update-system-prompt");
    expect(preload).not.toContain("token");
    expect(preload).not.toContain("ipcRenderer: ipcRenderer");
    expect(preload).not.toContain("send: (");
  });
});
